### ISSUE TITLE
Apt update issue on devkita64_devkitarm image

### ISSUE THREAD

**Issue by bladeoner** [devkitPro/docker#10]
Hi there, I hope you are doing fine.

Is it possible to change the update sources for apt update?

I'm using Ubuntu 20.04  and do a pull for the Docker image from Github to compile a project but I cannot install and update the necessary tools like python3 and lz4.
It might be that this also applies to the other docker images I didn't test.

As a work around I pull the docker image, remove /etc/apt/sources.list and replace the sources.list with the information below:

deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse

deb http://archive.canonical.com/ubuntu focal partner
deb-src http://archive.canonical.com/ubuntu focal partner

Thanks in advance.

**Comment by fincs** [comment]
The Docker images are based on Debian Stretch, not Ubuntu. I'm not sure what you're asking for. What project are you trying to compile; what CI system are you using? It would be helpful if you provided more information.

**Comment by bladeoner** [comment]
I'm trying to compile https://github.com/Atmosphere-NX/Atmosphere with a Github Workflow.

It sets up a Ubuntu 20.04 environment, which has it's repo's for apt pointed to the following for example:
deb-src http://azure.archive.ubuntu.com/ubuntu/ focal-updates main restricted

When I set up only Ubuntu 20.04 and do a sudo apt update and then a sudo apt install lz4 for example it will update the sources and download and install lz4.

When I set up Ubuntu 20.04 and then use the devkita64_devkitarm docker image on top of that, the repos are not pointed at http://azure.archive.ubuntu.com/ubuntu/ anymore but to a source where you can only download very old installation. When I do the same sudo apt install lz4 for example it won't find the file. So it seems that it's pointed now to a very old repo or something like that.

If you need more information I can share my YAML file.
