### ISSUE TITLE
Update docker image for libnx 4.0

### ISSUE THREAD

**Issue by HamletDuFromage** [devkitPro/docker#11]
Libnx 4.0 came out about a week ago and it's a pretty big update, with re-factoring and all. Could it be possible to update the image? 
Thank you

**Comment by HamletDuFromage** [comment]
@WinterMute I don't know if that's appropriate to @ you, but it would be neat if you could look into this. I've read your position on updates in a previous issue, but I believe that one is major enough to warrant doing it

**Comment by WinterMute** [comment]
docker image has been updated now.
