### ISSUE TITLE
Cannot be run in bitbucket pipeline

### ISSUE THREAD

**Issue by JoshuaBehrens** [devkitPro/docker#12]
I use this image to run CI in bitbucket pipeline but it fails as it cannot find target build. I use the GBA template in my project. This makefile defines build target when not in the build directory to call itself within the build directory again. Neat trick. Unfortunately a bitbucket pipeline runs in the directory /opt/atlassian/pipelines/agent/build and thus the makefile assumes it is already in the second call frame. It is not.

Why do I post it here when this is a problem of the GBA template? This is a CI/CD issue that is not easy to debug without looking further into the Makefiles which is an uneasy starter. As this is a CI/CD issue and these docker images should be used for CI/CD I think this place is right here.

What I expect? Just a hint somewhere in the getting started page or some other explanatory pages that this can be troublesome :)

**Comment by WinterMute** [comment]
You can just rename the build folder at the top of the Makefile here https://github.com/devkitPro/gba-examples/blob/master/template/Makefile#L23-L24

This is going to sound slightly sarcastic but it's a genuine question. What would make https://github.com/devkitPro/gba-examples/blob/master/template/Makefile#L13 clearer?

To be fair I didn't anticpate that the entire source tree would be extracted to a folder called build.

**Comment by JoshuaBehrens** [comment]
Renaming is an option, you are right, and this is currently my way although I renamed the directory in runs in. Thank you for mentioning the sarcasm hint :+1: My problem here is that there is no link to a possible issue. This is just descriptive for this specific Makefile. To be sure: I don't want to say that you should've known that issue before anyone else stumbling upon it. I cannot expect everyone testing there setups in a bitbucket pipeline. And I find it difficult myself to have a good solution for it. Although I have some ideas.

Btw. props to the comments in the Makefile. This makes it very easy to understand. Most Makefile writers - including myself sometimes - make a mess that is difficult to read again.

I didn't expect that the current directory I am in will make a Makefile fail either. This was super tricky to debug. The `-d` option shed some light onto it but still not obvious. The bitbucket logs are split into steps and the current directory is hidden in the setup step logs so an other point disguising hints.

Ideas for solution:

* Have a dedicated page for CI/CD. There is no need to mention every build system out there but a hint "how to suggest one" would be sufficient for others to share their code for it.
* Ensure that the check in https://github.com/devkitPro/gba-examples/blob/1623d16d044c5c27b610849210b3cc045c603e2c/template/Makefile#L64 is changed to e.g. a specific parameter that is given at call origin https://github.com/devkitPro/gba-examples/blob/1623d16d044c5c27b610849210b3cc045c603e2c/template/Makefile#L118
