### ISSUE TITLE
devkitARM: Locale does not support Unicode characters in paths

### ISSUE THREAD

**Issue by StephenCWills** [devkitPro/docker#17]
The latest devkitARM image is failing on `dkp-pacman -Syu --no-confirm`.
```
$ docker run devkitpro/devkitarm
:: Synchronizing package databases...
downloading dkp-libs.db...
 dkp-linux is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (3) 3ds-bulletphysics-2.87-5  3ds-examples-20210610-1  3ds-physfs-3.0.2-3

Total Download Size:    3.55 MiB
Total Installed Size:   9.54 MiB
Net Upgrade Size:      -0.36 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
downloading 3ds-bulletphysics-2.87-5-any.pkg.tar.xz...
downloading 3ds-examples-20210610-1-any.pkg.tar.xz...
downloading 3ds-physfs-3.0.2-3-any.pkg.tar.xz...
checking package integrity...
loading package files...
error: error while reading package /opt/devkitpro/pacman/var/cache/pacman/pkg/3ds-examples-20210610-1-any.pkg.tar.xz: Pathname can't be converted from UTF-8 to current locale.
error: failed to commit transaction (libarchive error)
Errors occurred, no packages were upgraded.
```

CI builds for 3DS are broken in DevilutionX with the same error.
https://app.circleci.com/pipelines/github/diasurgical/devilutionX/6348/workflows/254aae36-de94-4aa3-b5ed-e7e1ddabcc52/jobs/45643

**Comment by WinterMute** [comment]
This is fixed now but please don't run updates on CI. Please stick with the stock docker images and ask if there are updates you need that have not yet made it to our dockers.

**Comment by StephenCWills** [comment]
> This is fixed now but please don't run updates on CI. Please stick with the stock docker images and ask if there are updates you need that have not yet made it to our dockers.

Thanks! I've submitted a PR to fix our 3DS CI based on recent changes, and it removes the updates.
