### ISSUE TITLE
devkitPPC latest misses a date tag

### ISSUE THREAD

**Issue by lephilousophe** [devkitPro/docker#18]
Latest devkitPPC Docker image (digest b8a8d3d901fc) is only available through the latest tag.
Using the latest tag means that the toolchain will move every now and then.
Could you add a date tag for it as you already do for other devkit toolchains?

Thanks

**Comment by WinterMute** [comment]
A date tag has been added but you should really make best effort to use latest and not get stuck on old versions. The vast majority of projects I've encountered where people claimed they wouldn't work with latest tools have been relatively simple to update. Fixing warnings is always a good first step.

**Comment by lephilousophe** [comment]
Thank you very much.
Having a date tag is not to lag behind latest but to ensure build reproducibility of dependent images.
