### ISSUE TITLE
Containers on M1?

### ISSUE THREAD

**Issue by rhaleblian** [devkitPro/docker#22]
Hello hello, long time.

Appears that there isn't a `linux/arm64/v8` image on Hub, and building locally barfs when `/etc/mtab` isn't found...

How plausible is this goal?

**Comment by WinterMute** [comment]
We are currently running a donation drive to obtain M1 hardware so we can produce & test binaries on Apple Silicon. You can see progress on our website at https://devkitpro.org/

Are you specifically looking for docker images for Apple Silicon or would native binaries for that platform be preferable?

**Comment by rhaleblian** [comment]
Very good.

Docker images; my intent was to try containerizing a dev environment for dslibris, for the typical benefits.

I have access to other host architectures so I'm not showstopped.  An arm64 flavour for running on Pi would be good, I might be able to make that one.

Under M1 I have been using the tools from the pacman repo.  Didn't even think to consider whether they were native;
so many things run well under Rosetta 2.

And BTW I am using these images under GitHub Workflow CI and they are quite useful.

**Comment by rhaleblian** [comment]
y'know, I take this back.  I have plenty other architectures upon which to run containers.
arm64/v8 will come when it is predestined to do so; that is, at it's appointed time.
