### ISSUE TITLE
arm-none-eabi-gcc in Docker image suddenly no longer supports ObjC

### ISSUE THREAD

**Issue by Midar** [devkitPro/docker#26]
2 days ago, the CI for [ObjFW](https://github.com/ObjFW/ObjFW) broke. I saw that the Docker image for devkitpro/devkitarm was updated, and it fails ever since with
```
configure: error: Objective C compiler cannot create executables
```
Adding a `cat config.log` to see the actual invocation, I see:
```
arm-none-eabi-gcc: error: conftest.m: Objective-C compiler not installed on this system
```
So it seems the cc1objc binary is missing in the Docker image now?

Could you please push a new Docker image that includes cc1objc again? Thanks.

**Comment by WinterMute** [comment]
One day objective c support is likely to break to the point where it's not fixable. It's sorted for now but I'm not sure you can expect this support to be maintained forever.

**Comment by Midar** [comment]
Thanks, this works.

What are the problems you have / anticipate? ObjC support in GCC is tiny (cc1obj + libobjc). libobjc can even be left out (as nobody uses this), which means just the tiny compiler part remains.

Happy to help whereever needed!
