### ISSUE TITLE
Update Debian to `Bookworm`

### ISSUE THREAD

**Issue by MonsterDruide1** [devkitPro/docker#29]
These Dockerfiles are currently using `debian:bullseye-slim`. This version of Debian has been released in 2021 and will go EOL somewhere within this month:
<https://wiki.debian.org/DebianReleases>
> 11 | Bullseye | Release: 2021-08-14 | EOL: ~2024-07

An upgrade to Bookworm should be as simple as changing this line to `debian:bookworm-slim`:
https://github.com/devkitPro/docker/blob/master/toolchain-base/Dockerfile#L1

However, I cannot test the resulting containers properly, so opening a PR seems wrong to me. Please take a look at this, thanks!

**Comment by WinterMute** [comment]
Bullseye remains in LTS until 2026. We use Debian Oldstable for our docker images and have no plans to update to Stable.
