### ISSUE TITLE
[Suggestion] Use different source for toolchain-base container

### ISSUE THREAD

**Issue by H0neyBadger** [devkitPro/docker#8]
Hello, 
Small suggestion : It would be great to have a different source base for the **toolchain-base** container.
Currently the **debian:stretch-slim** is shipped with old versions of some tools (git, pyhton2, cmake)

I know that you are not supporting cmake and I perfectly understand why. 
I do not want to raise another thread on this topic. 

Unfortunately, since **downloads.devkitpro.org** is returning **"403 forbidden"** from Github CI, 
we are no longer able to use pacman from arch container. 

As far as I can see, the https://hub.docker.com/r/devkitpro/devkita64 is our best option. 
On the other hand, tools available from stretch repos are pretty old (especially for continuous integration).
So It would be great to have a different base like *debian buster* or the latest *arch* container.

let me know if you have any other recommendation. 
Regards,

**Comment by WinterMute** [comment]
We don't support use of pacman on CI. This wastes resources for everyoen, including github. 

We provide docker containers for this purpose at https://hub.docker.com/u/devkitpro

Something to consider when talking about "old versions of some tools" is that if you rely on absolute latest distros then you prevent people on older, still supported, distros from building your projects. Ultimately our philosphy at devkitPro is about improving accessibility and building a standardised environment. We don't intend to force people to upgrade or change their linux distro without a really good reason and neither should you.
